
const data = [
    { proID: 1, quantity:0, Features: `Key Features:<li>Display: 6.79" FHD+ Display</li><li>Resolution: 2460x1080, 396 ppiCertified eye-care Display</li><li>Processor: MediaTek Helio G91-Ultra</li><li>Refresh Rate: Up to 90Hz</li><li>Brightness: 450 nits (typ) 550 nits HBM</li><li>CPU: Cortex-A55+Cortex-A75</li><li>GPU: Mali-G52 MC2</li><li>Rear Camera: 108MP Super Clear Main camera</li><li>Film Camera | Custom Frame | 108MP Mode | HDR Mode | Night Mode </li><li>Front Camera: 13MP Front camera</li><li>Film Camera | HDR Mode | Soft Light Ring | Portrait Mode | Time Lapse</li><li>Battery & Charging: 5030mAh (typ) - Supports 33W fast charging | USB Type-C36 Months</li>`,key:``,BOX:``, descri:`<li>Security: Side fingerprint scanner - AI face unlock</li><li>Connectivity: SIM1 + Hybrid* (SIM or MicroSD)</li><li>Wi-Fi: 2.4GHz | 5GHz</li><li>Bluetooth: 5.4</li><li>Supports FM Radio with Headphone Jack</li><li>Operating System: Xiaomi Hyper OS</li><li>Sensors: Virtual Proximity Sensor | Ambient Light Sensor | Accelerometer |</li><li>Audio: 3.5mm headphone jack</li><li>Navigation & Positioning: GPS | Glonass | Galileo | Beidou</li><li>Dimensions: Height: 168.6mm - Width: 76.28mm - Thickness: 8.3mm - Weight: 205g</li>`,note: 'General Features:', cateory: 'New Arrival', img: '/PicturesFiles/extra_arrivals/Arrivales-1-1.jpg', price: 39999, productName: "Redmi 13 + Free Piston Basic",zoom1:"/PicturesFiles/extra_arrivals/Arrivales-1-1.jpg",zoom2:"/PicturesFiles/extra_arrivals/Arrivales-2.jpg",zoom3:"/PicturesFiles/extra_arrivals/Arrivales-3.jpg" },
    { proID: 2, quantity:0, Features: `Key Features:<li>Product Model: RD10/RD10M</li><li>Dimensions: 80x54x70mm</li><li>Antenna Type: 2×2 External Antenna with Enhanced Wi-Fi Coverage</li><li>Support up to 16 devices connected simultaneously\</li><li>Wireless Standards: IEEE 802.11b/g/n</li><li>Signal Rate: 2.4GHz, up to 300Mbps</li><li>Wireless Security: WPA-PSK/ WPA2-PSK encryption</li><li>Power Supply: 100-240V/0.35A</li>`,key:``,BOX:``, descri:`<li>Operating temperature: 0-40°C</li><li>Operating humidity: 10%-90%RH (non-condensing)</li><li>Storage temperature: -40-70°C</li><li>Storage humidity: 5%-90%RH (non-condensing)</li><li>Power consumption: 3.57W</li>`,note: 'Operating Environment:', cateory: 'New Arrival', img: '/PicturesFiles/extra_arrivals/Arrivales-4-1.jpg', price: 4299 , productName: "Xiaomi WiFi" ,zoom1:"/PicturesFiles/extra_arrivals/Arrivales-4-1.jpg",zoom2:"",zoom3:""},
    { proID: 3, quantity:0, Features: `Key Features:<li>Display: All Around Liquid Display</li><li>WQHD+ 6.73" AMOLED</li><li>Resolution:  3200 x 1440, 522 ppi</li><li>Brightness:   HBM 1000 nits (typ), 3000 nits peak brightness</li><li>Pro HDR display | support UltraHDR | Dolby Vision® | HDR10+ | 68 billion colors</li><li>Refresh rate: Dynamic 1-120Hz</li><li>Touch sampling rate: up to 240Hz</li><li>Processor: Snapdragon® 8 Gen 3 Mobile Platform</li><li>4nm power-efficient manufacturing process</li><li>GPU: Qualcomm® Adreno™ GPU</li><li>Rear Camera: Leica professional optical lens</li><li>Leica main camera LYT-900 -50MP | Leica 75mm floating telephoto camera 50MP- f/1.8</li><li>50MP mode (wide/ultra wide/telephoto/periscope)</li><li>Rear camera photography features: Leica Authentic Look | Leica Vibrant Look |</li><li>Rear camera video features: MasterCinema | Movie mode | Director mode |</li><li>Front Camera: 32MP in-display selfie camera | Portrait mode with bokeh and depth control</li><li>Battery: 5000mAh (typ) battery</li><li>Charging: 90W HyperCharge* | 80W wireless HyperCharge* | Reverse wireless charging</li><li>USB-C 3.2 Gen 2</li><li>Security: In-screen fingerprint sensor | AI face unlock</li>`,key:``,BOX:``, descri:`<li>Dimensions: Height: 161.4mmWidth: 75.3mmThickness: 9.20mm</li><li>Weight: 219.8g</li><li>Network & Connectivity: Dual SIM (nano SIM + nano SIM)</li><li>Wireless Networks: Xiaomi Surge T1 Tuner | Wi-Fi 7 capability | Supports NFC</li><li>Navigation & Positioning: GPS: L1+L5</li><li>Navigation & Positioning: GPS: L1+L5</li><li>Bluetooth 5.4, Dual-Bluetooth</li><li>Audio: Stereo speakers | 4-MIC Array | Dolby Atmos®</li><li>Video: MP4丨MKV丨WEBM丨3GP</li><li>Sensors: Proximity sensor | Ambient light sensor | Accelerometer | Gyroscope</li><li>Electronic compass | IR blaster | Barometer | Flicker sensor | X-axis linear vibration motor</li><li>Operating System: Xiaomi HyperOS</li> `,note: 'General Features:', cateory: 'New Arrival', img: '/PicturesFiles/extra_arrivals/Arrivales-5-1.jpg', price: 384999, productName: "Xiaomi 14 Ultra + Redmi Watch 3 Active", zoom1:"/PicturesFiles/extra_arrivals/Arrivales-5-1.jpg",zoom2:"/PicturesFiles/extra_arrivals/Arrivales-6.jpg",zoom3:""},
    { proID: 4, quantity:0, Features: `Key Features: <li>Display:Smooth 6.71” 90 Hz Display | Eye Care DC Dimming</li><li>Processors: Octa-core Unisoc T603 Chipest</li><li>Design: Stylish Glass Black Design | Elegant Circular Camera Deco</li><li>Refresh Rate: Up to 90Hz</li><li>Rear Camera: 8MP AI Dual Camera Paired with Auxiliary Lens | Portrait Mode</li><li>Front Camera: 5MP</li><li>| Selfie Beauty Mode | Soft Light Ring | Film Camera HDR Mode</li><li>Battery Capacity: 5000 mAh (typ) |  80% Capacity after 800 Charge Cycles</li><li>Micro SD Card Support upto 1TB Storage</li><li>Security: Side Fingerprint and Face Unlock | Everyday Durability</li><li>Durability with Corning Gorilla Glass</li>`,key:``,BOX:``, descri:``,note: '', cateory: 'New Arrival', img: '/PicturesFiles/extra_arrivals/Arrivales-8-1.jpg', price: 18399, productName: "Redmi A3x (3GB-64GB)" ,zoom1:"/PicturesFiles/extra_arrivals/Arrivales-8-1.jpg",zoom2:"/PicturesFiles/extra_arrivals/Arrivales-9.jpg",zoom3:"/PicturesFiles/extra_arrivals/Arrivales-10.jpg"},
    { proID: 5, quantity:0, Features: `Key Features:<li>Display: 6.67” WQHD+ 120Hz Flow AMOLED</li><li>Resolution: 3200*1440</li><li>Brightness: 700 nits (typ), 1200 nits(HBM brightness), 4000 nits (peak brightness)</li><li>Refresh rate: Up to 120Hz</li><li>Premium design with metal frame</li><li>All-round flagship by design</li><li>Processor: Snapdragon 8 Gen 2  : TSMC 4nm manufacturing process</li><li>CPU:  Cortex CPU, up to 3.19 GH</li><li>GPU:  Adreno GPU</li><li>AI: Qualcomm AI Engine</li><li>Powerful flagship performance</li><li>Rear Camera: 50MP main camera with OIS | 8MP ultra-wide camera | 2MP macro camera</li><li>Front Camera: 16MP front camera</li><li>Professional-level photography experience</li><li>Battery & Charging: 5000mAh (typ) battery | 120W HyperCharger </li><li>LiquidCool Technology 4.0 with IceLoop</li>`,key:``,BOX:``, descri:`<li>Security: In-screen fingerprint sensor | AI face unlock</li><li>Network & Connectivity: Dual SIM, dual standby | Supports 5G9/ 4G / 3G</li><li>Bluetooth: 5.3, Dual-Bluetooth</li><li>Audio: Stereo Dual speakers</li><li>IR blaster</li><li>Dimension: 160.86mm x 74.95mm x 8.21mm</li>`,note: 'General Features:', cateory: 'New Arrival', img: '/PicturesFiles/extra_arrivals/Arrivales-11-1.jpg', price: 17450, productName: "Poco F6 Pro (12GB+512GB) + Free Redmi 4 Lite",zoom1:"/PicturesFiles/extra_arrivals/Arrivales-11-1.jpg",zoom2:"/PicturesFiles/extra_arrivals/Arrivales-12.jpg",zoom3:"" },
    { proID: 6, quantity:0, Features: `Key Features:<li>Display:Smooth 6.71” 90 Hz Display | Eye Care DC Dimming</li><li>Processors: Octa-core Unisoc T603 Chipest</li><li>Design: Stylish Glass Black Design | Elegant Circular Camera Deco</li><li>Refresh Rate: Up to 90Hz</li><li>Rear Camera: 8MP AI Dual Camera Paired with Auxiliary Lens | Portrait Mode</li><li>Front Camera: 5MP</li><li>| Selfie Beauty Mode | Soft Light Ring | Film Camera HDR Mode</li><li>Battery Capacity: 5000 mAh (typ) |  80% Capacity after 800 Charge Cycles</li><li>Micro SD Card Support upto 1TB Storage</li><li>Security: Side Fingerprint and Face Unlock | Everyday Durability</li><li>Durability with Corning Gorilla Glass</li>`,key:``,BOX:``, descri:``,note: '', cateory: 'Smartphones', img: '/PicturesFiles/extra_arrivals/Arrivales-13-1.jpg', price: 18999, productName: "Redmi A3x (3GB-64GB) " ,zoom1:"/PicturesFiles/extra_arrivals/Arrivales-13-1.jpg",zoom2:"/PicturesFiles/extra_arrivals/Arrivales-14.jpg",zoom3:"/PicturesFiles/extra_arrivals/Arrivales-15.jpg"},
    { proID: 7, quantity:0, Features: `Key Features:<li>Display:  6.67" AMOLED display</li><li>Refresh Rate: Up to 120Hz</li><li>Brightness: 500nits(typ),1000nits(HBM brightness),1300nits(peak brightness)</li><li>Processor: MediaTek Helio G99-Ultra</li><li>CPU: Octa-core processor, up to 2.2GHz</li><li>GPU: Mali-G57 MC2</li><li>Rear Camera:  Triple Camera | Flagship-level | OIS Anti-shake Main camera</li><li>200MP main camera | 2MP macro camera | 8MP ultra wide camera</li><li>Front Camera: 16MP camera</li><li>Battery & Charging: 5000mAh battery (typ) | Supports 67W turbo charging  | 67W in-box charger</li><li>Water and Dust Resistant: IP54</li>`,key:``,BOX:``, descri:`<li>Security: In-screen fingerprint sensor | AI face unlock</li><li>Network & Connectivity: SIM1 + Hybrid* (SIM or MicroSD), supports 4G/ 3G/ 2G)</li><li>Sensors:  Proximity sensor | Ambient light sensor | Accelerometer | Electronic compass </li><li>Operating System: MIUI 14</li><li>Audio: Dual Speaker | Dolby Atmos® | 3.5mm headphone jack</li><li>Navigation & Positioning: GPS: L1 | GLONASS: G1 | BDS: B1 | Galileo E1</li><li>Dimensions: Height: 161.1mm - Width: 74.95mm - Thickness: 7.98mm - Weight: 188g</li>`,note: 'General Features:', cateory: 'Smartphones', img: '/PicturesFiles/extra_arrivals/Arrivales-16-1.jpg', price: 81999, productName: "Redmi Note 13 Pro (12GB-512GB)" ,zoom1:"/PicturesFiles/extra_arrivals/Arrivales-16-1.jpg",zoom2:"/PicturesFiles/extra_arrivals/Arrivales-17.jpg",zoom3:"/PicturesFiles/extra_arrivals/Arrivales-18.jpg"},
    { proID: 8, quantity:0, Features: `Key Features:<li>Display: 6.71” Dot Drop display</li><li>Resolution: 1650 x 720, 268 ppi</li><li>Brightness: 500 nits</li><li>Processors: MediaTek Helio G36</li><li>Refresh Rate: Up to 90Hz</li><li>CPU: Up to 2.2GHz</li><li>Rear Camera: 8MP AI Dual Camera</li><li>Auxiliary Lens | Film Camera | HDR Mode | Portrait Mode | Time Lapse</li><li>Flash & type: LED flash, monochrome</li><li>Front Camera: 5MP</li><li>Film Camera | HDR Mode | Soft Light Ring | Portrait Mode | Time Lapse</li><li>Battery Capacity : 5000 mAh (typ) | Support 10W Charging | 10W Type-C Inbox Charger</li><li>Security: Side Fingerprint Sensor | AI Face Unlock</li>`,key:``,BOX:``, descri:`<li>Network & Connectivity: Dual SIM + microSD | Support Dual 4G</li><li>Wireless Networks: 2.4GHz/5GHz Wi-Fi</li><li>Bluetooth 5.4</li><li>Navigation & Positioning: GPS | Glonass | Beidou | Galileo</li><li>Audio: 3.5mm headphone jack</li><li>Sensors: Virtual Ambient Light Sensor | Virtual Proximity Sensor | Accelerometer |</li><li>Operating System: Android 14 | 2 Android Major Updates | 3 Years of Security Patch Update</li><li>Dimensions: Height: 168.4mm - Width: 76.3mm - Thickness: 8.3mm</li>`,note: 'General Features:', cateory: 'Smartphones', img: '/PicturesFiles/extra_arrivals/Arrivales-19-1.jpg', price: 22999, productName: "Redmi A3 (4GB-128GB) + Free Piston Basic",zoom1:"/PicturesFiles/extra_arrivals/Arrivales-19-1.jpg",zoom2:"/PicturesFiles/extra_arrivals/Arrivales-20.jpg",zoom3:"/PicturesFiles/extra_arrivals/Arrivales-21.jpg" },
    { proID: 9, quantity:0, Features: `Key Features:<li>Display: 6.79" FHD+ Display</li><li>Resolution: 2460x1080, 396 ppi</li><li>Certified eye-care Display</li><li>Processor: MediaTek Helio G91-Ultra</li><li>Refresh Rate: Up to 90Hz</li><li>Brightness: 450 nits (typ) 550 nits HBM</li><li>CPU: Cortex-A55+Cortex-A75</li><li>GPU: Mali-G52 MC2</li><li>Rear Camera: 108MP Super Clear Main camera</li><li>Film Camera | Custom Frame | 108MP Mode | HDR Mode | Night Mode | Portrait Mode</li><li>Front Camera: 13MP Front camera</li><li>Film Camera | HDR Mode | Soft Light Ring | Portrait Mode | Time Lapse</li><li>Battery & Charging: 5030mAh (typ) - Supports 33W fast charging | USB Type-C</li>`,key:``,BOX:``, descri:`<li>Security: Side fingerprint scanner - AI face unlock</li><li>Connectivity: SIM1 + Hybrid* (SIM or MicroSD)</li><li>Wi-Fi: 2.4GHz | 5GHz</li><li>Bluetooth: 5.4</li><li>Supports FM Radio with Headphone Jack</li><li>Operating System: Xiaomi Hyper OS</li><li>Sensors: Virtual Proximity Sensor | Ambient Light Sensor | Accelerometer | Electronic Compass</li><li>Audio: 3.5mm headphone jack</li><li>Navigation & Positioning: GPS | Glonass | Galileo | Beidou</li><li>Dimensions: Height: 168.6mm - Width: 76.28mm - Thickness: 8.3mm - Weight: 205g</li>`,note: 'General Features:', cateory: 'Smartphones', img: '/PicturesFiles/extra_arrivals/Arrivales-22-1.jpg', price: 39999, productName: "Redmi 13 + Free Piston Basic",zoom1:"/PicturesFiles/extra_arrivals/Arrivales-22-1.jpg",zoom2:"/PicturesFiles/extra_arrivals/Arrivales-23.jpg",zoom3:"/PicturesFiles/extra_arrivals/Arrivales-24.jpg" },
    { proID: 10,quantity:0,Features: `Key Features<li>Display:  6.67" AMOLED display</li><li>Refresh Rate: Up to 120Hz</li><li>Brightness: 500nits(typ),1000nits(HBM brightness),1300nits(peak brightness)</li><li>Processor: MediaTek Helio G99-Ultra</li><li>CPU: Octa-core processor, up to 2.2GHz</li><li>GPU: Mali-G57 MC2</li><li>Rear Camera:  Triple Camera | Flagship-level | OIS Anti-shake Main camera</li><li>200MP main camera | 2MP macro camera | 8MP ultra wide camera</li><li>Front Camera: 16MP camera</li><li>Battery & Charging: 5000mAh battery (typ) | Supports 67W turbo charging </li><li>Water and Dust Resistant: IP54</li>`,key:``,BOX:``,descri:`<li>Security: In-screen fingerprint sensor | AI face unlock</li><li>Network & Connectivity: SIM1 + Hybrid* (SIM or MicroSD), supports 4G/ 3G/ 2G)</li><li>Sensors:  Proximity sensor | Ambient light sensor | Accelerometer | Electronic compass</li><li>Operating System: MIUI 14</li><li>Audio: Dual Speaker | Dolby Atmos® | 3.5mm headphone jack</li><li>Navigation & Positioning: GPS: L1 | GLONASS: G1 | BDS: B1 | Galileo E1</li><li>Dimensions: Height: 161.1mm - Width: 74.95mm - Thickness: 7.98mm - Weight: 188g</li>`, note: 'General Features:', cateory: 'Smartphones', img: '/PicturesFiles/extra_arrivals/Arrivales-25-1.jpg', price: 84999, productName: "Redmi Note 13 Pro (12GB-512GB) + Free Redmi Buds 4 Active" ,zoom1:"/PicturesFiles/extra_arrivals/Arrivales-25-1.jpg",zoom2:"/PicturesFiles/extra_arrivals/Arrivales-26.jpg",zoom3:"/PicturesFiles/extra_arrivals/Arrivales-27.jpg"},
    { proID: 11,quantity:0,key:``, BOX:``,descri:``, Features: `<li>Output: 120W max output</li><li>Case material: High temperature resistant material</li><li>High altitudes: Suitable for use at 2000m altitudes</li><li>Compatibility: *Safe charging for most Type-C port laptops on the market, with smart fast charging.</li><li>Protection from:</li>`, note: `Description: `,descri: `MI 33W Wall Charger (TYPE-A + TYPE-C)- the latest power brick from Xiaomi for fast and powerful charging. The wall charger offers a high-power fast-charging experience with its maximum output capacity of 33W. The charging brick also features a PD fast charging protocol, that allows the charger to be compatible with various other devices, either fast charge your Xiaomi smartphone or an iPhone. The convenience of the charger doesn't end here, Xiaomi also provides a USB-C and USB-A output port that expands the array of smartphone that can be charged using it. The compact and portable design embodies many safety features, you have protection against high voltage, short circuit, electromagnetic field, overheating, static electricity, lightning, current overflow, and low voltage. The lightweight MI 33W Wall Charger (TYPE-A + TYPE-C) weighs only 0.1 kg.`, cateory: 'Power Bank', img: '/PicturesFiles/extra_arrivals/Arrivales-28-1.jpg', price: 3999, productName: "MI 33W Wall Charger (TYPE-A + TYPE-C)" ,zoom1:"/PicturesFiles/extra_arrivals/Arrivales-28-1.jpg",zoom2:"",zoom3:""},
    { proID: 12,quantity:0,BOX:`PACKAGE CONTENTS:`,key:`<li>Xiaomi 37W Dual Port Car Charger</li> <li>User Manual </li>`, descri:`Rushing from home to work or out on a travel vogue there is one thing we don’t want you to worry about at all phone charging! The Mi 37 W Dual Port Car Charger will let you fast charge your smartphones just like normal. Just use a good charging cable of choice and it is ready to go. Compatible with all mainstream mobile models. And guess what, you won’t even have to fight your siblings for a slot as it offers two equally powerful charging ports.Here at Mistore.pk our Mi fans consider it to be their best travel partner! Scroll down for their flooded reviews. Buy here from Mistore.pk and get a 10-Days Eco Warranty.`, Features: `<li>Single port 27W MAX fast flash charging</li><li>Dual port 37W MAX high speed output</li><li>Multiple protections are safer</li><li>LED power indicator clearly indicates the location of the interface and can be seen at night</li><li>Compatible with mainstream models</li><li>Streamlined black matte body</li><li>Positive and negative anti-skid shrapnel</li>`, note: 'Note: Maximum charging output may vary from device to device based on the firmware and fast charging capability.', cateory: 'Power Bank', img: '/PicturesFiles/extra_arrivals/Arrivales-29-1.png', price: 2390, productName: "Mi Type C Charger 20W" ,zoom1:"/PicturesFiles/extra_arrivals/Arrivales-29-1.png",zoom2:"",zoom3:""},
    { proID: 13,quantity:0, Features: `<li>Port: USB Type-C</li><li>Input: 5V/3A 9V/2A 12V/2A</li><li>15V/1.8A 20V/1.35A, 12800mAh 474Wh</li><li>Output: 20W MAX</li><li>Dimensions: 117.2x73.4x91.7mm</li><li>Box Content: Wireless Charger, cable, adapter, pedestals, user guide.</li>`,key:`<li>Mi 20W Wireless Car Charger</li><li>Adhesive Mount</li><li>USB-A to USB-C Cable</li><li>User Manual</li>`, BOX:`INSIDE THE BOX`,descri:`What can be better than a 20 Watts car charger? A 20 Watts Wireless car charger of course! The Mi 20W Wireless Car Charger has been our hot selling item at MiStore.pk ever since it was introduced in the tech industry. Although the entire range of Xiaomi’s chargers is commendable, but this wireless car charger is exceptional. It is a compact charger that fits perfectly in your car via an adapter after which all you need to do is click your phone in its arms and witness the magic. Even amazing is the fact that it allows you to use your mobile as if on a car mobile holder while charging it simultaneously. Isn’t that just what we all need? Xiaomi has a vision to facilitate its users in every way possible and MiStore.pk is onto delivering Xiaomi at its best to Pakistan. Buy Mi 20W Wireless Car Charger now!`,note: 'Note: Maximum charging output may vary from device to device based on the firmware and fast charging capability.', cateory: 'Power Bank', img: '/PicturesFiles/extra_arrivals/Arrivales-30-1.jpg', price: 11499, productName: "Xiaomi 120W Charging Combo (Type-A)",zoom1:"/PicturesFiles/extra_arrivals/Arrivales-30-1.jpg",zoom2:"",zoom3:"" },
    { proID: 14,quantity:0, Features: `<li>Input: 90~264Vac ~ 47/63Hz, 1.1A</li><li>Output port: USB-C + USB-A</li><li>Output: USB-C : 5V/3A, 9V/3A, 11V/3A, 12V/2.5A, 15V/2A，20V/1.65A，33W MAX</li><li>USB-A: 5V/3A, 9V/3A, 12V/2.25A，27W MAX</li><li>Turbo Charging: Supports only Type-C to Type-C</li><li>Dimensions: 83.7mm x 48mm x 28mm</li>`,key:``, BOX:``,descri:`MI 33W Wall Charger (TYPE-A + TYPE-C)- the latest power brick from Xiaomi for fast and powerful charging. The wall charger offers a high-power fast-charging experience with its maximum output capacity of 33W. The charging brick also features a PD fast charging protocol, that allows the charger to be compatible with various other devices, either fast charge your Xiaomi smartphone or an iPhone. The convenience of the charger doesn't end here, Xiaomi also provides a USB-C and USB-A output port that expands the array of smartphone that can be charged using it. The compact and portable design embodies many safety features, you have protection against high voltage, short circuit, electromagnetic field, overheating, static electricity, lightning, current overflow, and low voltage. The lightweight MI 33W Wall Charger (TYPE-A + TYPE-C) weighs only 0.1 kg.`,note: `Description:`, cateory: 'Power Bank', img: '/PicturesFiles/extra_arrivals/Arrivales-31-1.jpg', price: 2699, productName: "Mi 37W Dual port Car Charger" ,zoom1:"/PicturesFiles/extra_arrivals/Arrivales-31-1.jpg",zoom2:"",zoom3:""},
    { proID: 15,quantity:0, Features: `<li>Model: AD201EU</li><li>Input: 100-240V~50/60HZ 0.5A</li><li>Output Port: USB-C</li><li>Output: 5V/3A, 9V/2.22A, 12V/1.67A, 20W Max Output</li><li>Support: Mi Smartphone 18W Fast Charging - iPhone 8~10 18W & iPhone 12 20W PD</li><li>Charge iPhone: 60% in 30min</li><li>Protocol: PD3.0, QC3.0, AFC, FCP</li><li>Interface: USB-C interface support bidirectional insertion</li><li>Dimensions: 38 x 22.2 x 61.2 mm (Exclude Pins)</li><li>Weight: 52g</li>`,key:``, BOX:``,descri:``,note: `The Mi Type C Charger 20 W is a fast charger that is compatible with all mobile devices however it is specifically designed to wave off the tension of iPhone users as it charges iPhones with the same excellence as it charges android phones. This fast charger can consider to be your one solution to all charging problems. It has a USB-C input port to support ultra-fast charging for your android and iOS phones. `, cateory: 'Power Bank', img: '/PicturesFiles/extra_arrivals/Arrivales-32-1.jpg', price: 1999, productName: "Mi Type C Charger 20W" ,zoom1:"/PicturesFiles/extra_arrivals/Arrivales-32-1.jpg",zoom2:"",zoom3:""},
    { proID: 16,quantity:0, Features: `Key Features:<li>Product Model: M2314W1</li><li>Screen size and type: 1.97 inches, AMOLED color Square Screen</li><li>Screen Resolution: 390 × 450, Supports full screen Touch Operation</li><li>Screen Brightness: Up to 600nits, supports automatic brightness adjustment</li><li>Sensors: Acceleration sensor | Gyroscope sensor | Optical heart rate and blood oxygen sensor |Ambient light sensor | Geomagnetic sensor</li><li>Sports Mode: 150+ | Voice coaches</li><li>Faces: 200+ fashionable Watch Dials</li><li>Waterproof Level: 5ATM</li><li>Data Connections: Support GNSS, support NFC Region/Country dependent, Bluetooth™ 5.3</li>`,key:``, BOX:``,descri:`<li>Vibration motor: Support</li><li>Battery Capacity: 470mAh</li><li>Battery Life: 20 days long battery life* - One charge, three weeks worry-free</li><li>Battery Type: Lithium-ion polymer battery</li><li>Charging time: About 85 minutes</li><li>Applicable wrist size: 135mm-205mm</li><li>Wristband material: TPU</li><li>Main body net weight: Approximately 31.5g (excluding wrist strap)</li><li>Body size: 47.58 × 41.12 × 10.5 mm (excluding heart rate boss)</li><li>Support System: Xiaomi HyperOS, Android 8.0 or iOS 12.0 and above</li><li>Support App: Xiaomi Sports Health</li>`,note: 'General Features:', cateory: 'Gear & Devices', img: '/PicturesFiles/extra_arrivals/Arrivales-35-1.jpg', price: 24499, productName: "Redmi Watch 4" ,zoom1:"/PicturesFiles/extra_arrivals/Arrivales-35-1.jpg",zoom2:"/PicturesFiles/extra_arrivals/Arrivales-36.jpg",zoom3:""},
    { proID: 17,quantity:0, Features: `Key Features:<li>Display: 1.83 inch LCD Display</li><li>Supports Bluetooth®️ phone call*</li><li>Resolution: 240×280 pixel</li><li>Brightness: up to 450 nits, adjustable</li><li>Water Resistant: 5ATM</li><li>Classic rectangle shaped case - Metallic finish middle frame</li><li>Watch Faces: 200+ Stylish watch faces</li><li>Workout Modes: 100+ Fitness Modes</li><li>Sensors: Heart rate sensor (with blood oxygen sensor), accelerometer</li><li>Battery: 289mAh - Typical use time: 12 days - Heavy use time: 8 days</li><li>Charging Port: Magnetic</li>`,key:``, BOX:``,descri:`<li>Microphone: Supported</li><li>Speaker: Supported</li><li>Bluetooth® 5.3</li><li>Compatibility: Supports smartphones with Android 6.0 or ios 12.0 and above</li><li>Strap Size: 135～200mm</li><li>Dimensions: Height:46.94mm x Width: 38.88mm x Thickness10.94mm (Exclude the strap and protrusions)</li>`,note: 'General Features:', cateory: 'Gear & Devices', img: '/PicturesFiles/extra_arrivals/Arrivales-37-1.jpg', price: 10499 , productName: "Redmi Watch 3 Active" ,zoom1:"/PicturesFiles/extra_arrivals/Arrivales-37-1.jpg",zoom2:"/PicturesFiles/extra_arrivals/Arrivales-38.jpg",zoom3:""},
    { proID: 18,quantity:0, Features: `Key Features:<li>Display Size and Type :  Massive 1.74", AMOLED Touch Display | color square screen</li><li>Display Resolution: 336 x 480, 336PPI with full-screen touch</li><li>Screen Brightness: Maximum 600 nits, with auto brightness adjustment | All-new quick release structure with metallic frame</li><li>Data Connection Supports GNSS, Bluetooth® 5.3</li><li>Haptic Motor: Rotor motor</li><li>Operating System: Android 8.0 or iOS 12.0 and above</li><li>Compatible Apps: Mi Fitness app</li><li>Supports 150+ sports modes, built-in GNSS</li><li>Watch faces: Hundreds of stylish watch faces</li><li>Water resistance Rating: 5ATM</li><li>Health Monitoring: Daily activity record | All-day heart rate monitoring | All-day oxygen saturation monitoring | Women's menstruation reminders | Breathing exercises | 3D warm-up & cool-down coach | A "personal trainer" on your wrist Vitality score | Smart running mode | On-wrist running courses</li>`,key:``, BOX:``,descri:`<li>Battery Capacity 289mAh</li><li>Charging Time: Approx. 80min | Up to 14-day battery life</li><li>Sensors: Accelerometer | Gyroscope | Optical heart rate and pulse oximeter | Ambient light sensor</li><li>Cover material: GG3 reinforced glass</li><li>Shell Material: High-strength fiber polymer + NCVM</li><li>Net Weight: Approx. 22.5g (weight without the strap)</li><li>Dimensions: 46 x 33.35 x 9.99mm (excluding the heart rate sensor)</li>`,note: 'General Features:', cateory: 'Gear & Devices', img: '/PicturesFiles/extra_arrivals/Arrivales-39-1.jpg', price: 16499, productName: "Xiaomi Smart Band 8 Pro" ,zoom1:"/PicturesFiles/extra_arrivals/Arrivales-40.jpg",zoom2:"/PicturesFiles/extra_arrivals/Arrivales-39-1.jpg",zoom3:""},
    { proID: 19,quantity:0, Features: `<li>Display: 1.62", AMOLED Touch Display</li><li>Resolution: 192 x 490, 326 PPI</li><li>Screen Brightness: Up to 600 nit</li><li>Case material: 2.5D reinforced glass case</li><li>Adaptive Display Brightness: Support ambient light sensors that allow the display brightness to automatically adjust for your eyes</li><li>High Refresh Rate: New chipset that supports 60Hz high refresh rate, smooth usage</li><li>Ambient light sensor: Yes</li><li>New Pebble Mode: Professional running experience</li><li>Workout Mode: 150+ workout modes</li><li>Watch faces: 200+ different colorful watch faces, also include fun games watch faces</li><li>Water resistant level: 5 ATM</li><li>Health Monitoring: All-day SpO2 level tracking, continuous sleep monitoring, 24-hour heart rate monitoring, and sleep breathing monitoring.</li>`,key:``, BOX:``,descri:`<li>Battery Life: Up to 16-days battery life for normal daily use</li><li>Standby Time: 16 days for normal use and 6 days for AOD use</li><li>Charging Time: Support 2C quick charge, fully charged within 1hour</li><li>Sensor: 3-axis accelerometer + 3-axis gyroscope sensors PPG sensor</li><li>Wireless Connectivity: BT5.1 BLE</li><li>System Requirements: Android 6.0，iOS12 or above</li><li>Wrist strap material: TPU</li><li>Supported App: Mi Fitness</li><li>Dimensions: 48*22.5*11mm</li>`,note: 'General Features:', cateory: 'Gear & Devices', img: '/PicturesFiles/extra_arrivals/Arrivales-41-1.jpg', price: 8999 , productName: "Xiaomi Smart Band 8" ,zoom1:"/PicturesFiles/extra_arrivals/Arrivales-41-1.jpg",zoom2:"/PicturesFiles/extra_arrivals/Arrivales-42.jpg",zoom3:""},
    { proID: 20,quantity:0, Features: `Key Features:<li>Display:1.43" AMOLED display</li><li>Display Resolution: 466 × 466, 326PPI</li><li>Battery Capacity: 486mAh | Versatile bezel for limitless customization</li><li>Battery Type: Lithium-ion polymer battery</li><li>Battery Life: Typical usage with Andriod system: 15 days | Typical usage with iOS system:</li><li>AOD usage: 5 days</li><li>Water Resistance Rating: 5ATM</li><li>Operating System Android 8.0 or iOS 12.0 and above | Supports 150+ sports modes, built-in L1+L5 dual-band GNS</li><li>Health Monitoring:  All-day heart rate monitoring | All-day oxygen saturation monitoring | </li><li>Watch faces: Hundreds of stylish watch faces</li>`,key:``, BOX:``,descri:`<li>Product Material: Aluminum alloy frame, stainless steel bezel, corning glass</li><li>Strap Material: Fluororubber</li><li>Product Dimensions: 47mm × 47mm × 12mm</li><li>Product Weight: 44g (without strap)</li><li>Adjustable Strap Length: 140–210mm</li><li>Sensors: Heart rate sensor (with blood oxygen sensor), accelerometer, gyroscope,</li><li>Charging Port: 2-Pin magnetic charging dock</li><li>Wireless Connectivity Bluetooth® 5.2</li><li>Satellite Positioning Systems BeiDou, GPS, GLONASS, Galileo, QZSS</li>`,note: 'General Features:', cateory: 'Gear & Devices', img: '/PicturesFiles/extra_arrivals/Arrivales-33-1.jpg', price: 31999, productName: "Xiaomi Watch S3",zoom1:"/PicturesFiles/extra_arrivals/Arrivales-34.jpg",zoom2:"/PicturesFiles/extra_arrivals/Arrivales-33-1.jpg",zoom3:""},
    { proID: 21,quantity:0, Features: `<li>Product model: MJSXJ03HL</li><li>Resolution: 2304 x 1296 pixel</li><li>Image quality: Ultra-clear 2K</li><li>Audio: Two-way voice calls</li><li>Sensor: Motion detection</li><li>Video encoding: H.265</li><li>Operating temperature: -10°C to 50°C</li><li>Rated input: 5V〜1A</li><li>Lens angle: 125°</li><li>Wireless connection: Wi-Fi IEEE 802.11b/g/n 2.4GHz</li><li>Storage: Micro SD card</li><li>Compatible with: Android 6.0 & iOS 11.0 or above</li><li>Product dimensions: 60 x 48 x 67.5 mm</li>`,key:``, BOX:``,descri:`<li>Camera</li><li>Accessories: Charging Cable, Magnetic Base, Metallic Sticker.</li><li>User Manual</li>`,note:`PACKAGE CONTENTS:`, cateory: 'Camera & Visual', img: '/PicturesFiles/extra_arrivals/Arrivales-45-1.jpg', price: 7999, productName: "Xiaomi Outdoor Camera AW200" ,zoom1:"/PicturesFiles/extra_arrivals/Arrivales-45-1.jpg",zoom2:"",zoom3:"" },
    { proID: 22,quantity:0, Features: `<h2>Outdoor Camera AW200</h2><br><h4>Key Features:</h4><br><li>Resolution: 1920x1080p high-resolution </li><li>Lens angle: 120°</li><br><h6>Special Features:</h6> <br> <li>Waterproof Rating: IP65 – Dust and Water Resistant</li><li>Colour Night Vision</li><li>Two way voice calls</li> <li>Motion Detection</li><li>Works with Alexa & Google Home</li><li>Detachable base</li><li>Time-Lapse photography</li><li>Daytime magnification without blurring</li><li>ƒ/1.6 large aperture</li><li>H.265 video coding</li><li>940nm infra-red night vision without the visible red light </li><li>AI human detection technology filters out unwanted alarms caused by non-human movements.</li><li>Micro SD card | Cloud storage | Fully encrypted data transmission | AES-128 encryption via the cloud </li>` ,BOX:`General Features:`,key:`<li>Product Model no: MJSXJ05HL</li><li>Rated Input: 5V/1A</li><li>Operating temperature: -20°C to 50°C</li><li>Wireless connection: Wi-Fi IEEE 802.11b/g/n 2.4GHz</li><li>Power extension leads: Wire size: 18 - 20 - 22 – 24</li><li>Maximum Length allowed: 34m - 26m - 18m - 8m</li>`,descri:``,note: ``, cateory: 'Camera & Visual', img: '/PicturesFiles/extra_arrivals/Arrivales-43-1.jpg', price: 13999, productName: "Xiaomi Outdoor Camera AW300" ,zoom1:"/PicturesFiles/extra_arrivals/Arrivales-43-1.jpg",zoom2:"",zoom3:""},
    { proID: 23,quantity:0, Features: `<p>2K Full-HD | Smart Full-Color Night Vision | Focus Zone Setting | IP66 Weather-resistant | Audible and visual alarm protection | IP66 water and dust resistant | 24h real-time monitoring | Two-way voice intercom | Split-screen viewing for multiple cameras.</p><li>Rated Input: 12V ⎓1A</li><li>Field of View(FoV): 101.7°</li><li>Resolution: 2304×1296</li><li>Aperture: F2.0</li><li>Video Codec: H.265</li><li>Night Vision Light: 850nm IR light ×2, LED spotlight ×2</li><li>Operating Temperature for Camera: -30℃~60℃</li><li>Wireless Connectivity: Wi-Fi IEEE 802.11b/g/n 2.4GHz</li><li>Storage Function: microSD Card(from 32GB to 256GB supported)/cloud storage</li><li>Storage Function: microSD Card(from 32GB to 256GB supported)/cloud storage</li><li>Net Weight: 249g</li>`,key:``, BOX:``,descri:``,note: '', cateory: 'Camera & Visual', img: '/PicturesFiles/extra_arrivals/Arrivales-44-1.jpg', price: 18499, productName: "Xiaomi Outdoor Camera AW300",zoom1:"/PicturesFiles/extra_arrivals/Arrivales-44-1.jpg",zoom2:"",zoom3:"" },
    { proID: 24,quantity:0, Features: `<h5>2K Security Camera Ultra HD</h5><br><h6>Key Features:</h6><br><li>Resolution: 2304 × 1296</li><li>Ultra-Clear HD: Super clear 2K image quality and upgraded AI</li><li>Standard HD resolution: 1920 × 1080=1080p (2 megapixel);</li><li>Upgraded ultra-clear HD resolution: 2304 × 1296=1296p (3 megapixel)</li><li>3 megapixel | F1.4 large aperture | Full colour in low-light | AI human detection</li><li>Aperture: F1.4 for clear picture</li><li>Two-way voice calls in real time</li><li>H.265 video encoding saves storage and bandwidth</li><li>6P Lens for Higher Quality Display</li><li>Simply ask your Mi Smart Clock to show real-time video output from your camera*</li><li>The AI human detection effectively filters false alarms</li>`,key:``, BOX:``,descri:`<li>Product Model No: XMC01</li><li>Compatible with: Android 4.4 or iOS 9.0 and above</li><li>Wireless connection: Wi-Fi IEEE 802.11b/g/n 2.4GHz</li><li>Product net weight: 327g</li><li>Power input: 5V=1A</li><li>Video encoding: H.265</li><li>Video encoding: H.265</li><br><h6>PACKAGE CONTENTS: </h6><li>Smart Camera C300</li><li>Charging Cable</li><li>Wall Mounting Kit</li><li>User Manual</li>`,note: 'General Features:', cateory: 'Camera & Visual', img: '/PicturesFiles/extra_arrivals/Arrivales-46-1.jpg', price: 14199, productName: "Xiaomi Smart Camera C300" ,zoom1:"/PicturesFiles/extra_arrivals/Arrivales-46-1.jpg",zoom2:"",zoom3:""},
    { proID: 25,quantity:0, Features: `<li>Model: MJSXJ11CM</li><li>Resolution: 2560 × 1440</li><li>Ultra-clear video in 2.5K with 4MP camera | 360° rotation | AI human detection</li><li> Real-time two-way voice calling with smart noise reduction enabled for clear conversations</li><li> Night vision with no visible red glow for clearer and safer monitoring</li><li> Support flat and inverted mounting</li><li> Operating Temperature：-10℃ to</li><li>Net Weight: Approx.318g</li><li> Input: 5V⎓2A</li><li> ltem Dimensions: 119 × 78 × 78mm</li><li>Storage: microSD card (up to 256 GB) | Local + cloud storage is more secure</li><li> Wireless Connectivity: Wi-Fi IEEE 802.11a/b/g/n 2.4 / 5GHz</li><li>Fully encrypted to protect your privacy</li>`,key:``, BOX:``,descri:``,note: '', cateory: 'Camera & Visual', img: '/PicturesFiles/extra_arrivals/Arrivales-47-1.jpg', price: 18899, productName: "Mi Camera 2K Magnetic Mount" ,zoom1:"/PicturesFiles/extra_arrivals/Arrivales-47-1.jpg",zoom2:"",zoom3:""},
    { proID: 26,quantity:0, Features: `<h6>Key Features:</h6><br><li>Flagship sound quality, custom-made ceramic ring coaxial dual drivers</li><li>SoundID ear canal calibration | Dual-mode independent spatial audio </li><li>52dB flagship active noise cancellation* | 3-stop noise reduction/transparency mode adjustment</li><li>3 Mai AI self-developed call resistance against wind noise</li><li>Headphone input parameters: 5V  ⎓  160mA MAX (single earphone)</li><li>Charging box input parameters: 5V  ⎓  700mA MAX</li><li>charging interface: Type-C</li><li>single earphone Music life: about 10 hours (noise reduction off)</li>`,key:``, BOX:``,descri:`<li>Battery life with charging box: about 38 hours (noise reduction off)</li><li>Wireless connection: Bluetooth 5.3</li><li>Bluetooth protocol: Bluetooth® Low Energy / HFP / A2DP / AVRCP</li><li>Working distance: 10m (barrier-free open environment)</li><li>Speaker impedance: 16Ω</li>`,note: 'General Features:', cateory: 'Audio', img: '/PicturesFiles/extra_arrivals/Arrivales-51-1.jpg', price: 17499, productName: "Redmi Buds 5 Pro" ,zoom1:"/PicturesFiles/extra_arrivals/Arrivales-51-1.jpg",zoom2:"/PicturesFiles/extra_arrivals/Arrivales-52.jpg",zoom3:"/PicturesFiles/extra_arrivals/Arrivales-53.jpg"},
    { proID: 27,quantity:0, Features: `<li>Product Model: M2232E1</li><li>Advanced Bluetooth® 5.3 for stable connection | Convenient connectivity with Google Fast Pair*</li><li>12mm dynamic driver for powerful bass </li><li>Charge 10 minutes for up to 110 minutes music*</li><li>Noise cancellation for calls</li><br><ul>Dimensions:<li>Single Earbud: 31.1×20.9×22.5mm</li><li>Charging Case: 63.2×53.4×24mm</li></ul><ul>Weight:<li>Single Earbud: 3.65g</li><li>Charging Case: 34.7g</li><li>Total Weight: 42g</li></ul><ul>Battery:<li>Earbuds: 1040 (34mah)</li><li>Charging Case: 440mAh</li><li>28-hour ultra-long battery life with charging case </li><li>5 Hours Battery Life on a single charge</li></ul><ul>Charging:<li>Charging Port: Type-C</li><li>Earbud input parameters: 5V⎓0.10A</li><li>Charging case input parameters: 5V⎓0.50A</li><li>Charging case output parameters: 5V⎓0.20A</li></ul><ul>Connectivity:<li>Wireless connection: SBC</li><li>Bluetooth protocols: HFP/A2DP/AVRCP</li><li>Communication Range: 10m</li><li>Speaker impedance: 32Ω</li></ul>`,key:``, BOX:``,descri:``,note: '', cateory: 'Audio', img: '/PicturesFiles/extra_arrivals/Arrivales-48-1.jpg', price: 10999, productName: "Redmi Buds 5" ,zoom1:"/PicturesFiles/extra_arrivals/Arrivales-48-1.jpg",zoom2:"/PicturesFiles/extra_arrivals/Arrivales-49.jpg",zoom3:"/PicturesFiles/extra_arrivals/Arrivales-50.jpg"},
    { proID: 28,quantity:0, Features: `<li>Product model no: M2231E1</li><li>Bluetooth: Bluetooth®5.3</li><li>Supports: Supports Google Fast Pair*</li><li>12mm Dynamic Driver</li><li>Battery with Case: Up to 20 hours battery life with charging case*</li><li>Water Resistance: IP54 water-resistance</li><br><ul>Size and Weight:<li>Single earbuds weight: 3.92g</li><li>Single earbuds size: 32.24×18.22×19.63mm</li><li>Charging case weight: Around 26.7g</li><li>Charging case size: 55.6×47.3×22.2m</li><li>Total weight: 35g</li></ul><ul>Charging:<li>Charging Port: Type-C</li><li>Earbud input parameters: 5V⎓0.10A</li><li>Charging case input parameters: 5V⎓0.50A</li><li>Charging case output parameters: 5V⎓0.20A</li></ul><ul>Connectivity:<li>Wireless connection: SBC</li><li>Bluetooth protocols: HFP/A2DP/AVRCP</li><li>Communication Range: 10m</li><li>Speaker impedance: 32Ω</li></ul>`,key:``, BOX:``,descri:``,note: '', cateory: 'Audio', img: '/PicturesFiles/extra_arrivals/Arrivales-54-1.jpg', price: 5499, productName: "Redmi Buds 4 Lite" ,zoom1:"/PicturesFiles/extra_arrivals/Arrivales-54.jpg",zoom2:"/PicturesFiles/extra_arrivals/Arrivales-54-1.jpg",zoom3:""},
    { proID: 29,quantity:0, Features: `<h4>Key Features:</h4><br><li>Noise Reduction: 46dB deep Noise Reduction | Flagship level</li>2kHz wide frequency noise reduction range | Xiaomi’s self-developed anti-wind noise algorithm<li></li>12.4mm titanium-plated dynamic coil | Cloud gap light breathing light bar<li>Bluetooth protocol: Bluetooth® Low Energy / HFP / A2DP / AVRCP</li><li>Wireless connection: Bluetooth™ 5.3</li><li>Charging interface: Type-C</li><li>Speaker impedance: 32Ω</li><li>Communication distance: 10m (barrier-free open environment)</li><li>Test Certification: Passed the test and certification of China Institute of Metrology</li>`,key:`The charging case is light on your pockets. The Redmi Buds 5 price in Pakistan does not justify the exceptional features it offers.`, BOX:`Xiaomi Redmi Buds 5 is a great innovation that will amaze Xiaomi fans with its stunning features. You can talk to your loved ones anytime you want with the high noise reduction feature. You won't get disturbed as it blocks 99.5% of background noise. Wear it for an unlimited time as it is super comfortable for ears. You can enjoy your favourite tracks, movies and reels with an immersive sound experience without worrying about charging. The long-lasting battery will surely rock you up! The design is elite and classy which enhances your style statement. Gaming enthusiasts will cheer up with its low-latency gaming mode that allows audio-visual synchronisation.`,descri:`<li>Battery life including charging box: 40 hours long battery life (noise reduction off)</li><li>Single earphone music life: About 10 Hours (noise reduction off)</li><li>Charging box input parameters: 5V  ⎓  500mA</li><li>Earphones input parameters: 5V  ⎓  150mA (single earphone)</li><li>Material: Plastic</li><li>Design: Rod-shaped design | Comfortable wearing experience</li>`,note: 'General Features:', cateory: 'Audio', img: '/PicturesFiles/extra_arrivals/Arrivales-56-1.jpg', price: 4999, productName: "Redmi Buds 4 Active" ,zoom1:"/PicturesFiles/extra_arrivals/Arrivales-58.jpg",zoom2:"/PicturesFiles/extra_arrivals/Arrivales-56-1.jpg",zoom3:""},
    { proID: 30,quantity:0, Features: `<li>Aluminum sound chamber</li><li>Press for play</li><li>Cable Length 1.25m</li><li>Plug Type 3.5mm Nickel Plated</li><li>Speaker Impedance: 32Ω</li><li>Rated Power: 5 mW</li><li>Weight 14g</li><li>Improved 3rd gen balanced damping.</li>`,key:``, BOX:``,descri:``,note: 'Not into Bluetooth audio gadget? No worries the Mi piston basic handsfree is a classic handsfree to fit your needs. This wired handsfree is designed to ace perfection, durability, and quality all at the same time. An aluminum framed beauty designed for android phones. A buttoned mouthpiece allows you to play and paused at a press and more over communicate freely and easily. The 3rd gen balanced damping makes your audio experience one of a kind. This coupled with the fit-in-ear plug design takes you to another musical dimension. Available in two classy colors Black and Silver to match your class. Mistore.pk is proud to make record-breaking sales of this item since its arrival. Scroll down for all the amazing reviews from our Mi fans. Moreover, buy now from Mistore.pk and get a 10-Days Eco Warranty.', cateory: 'Audio', img: '/PicturesFiles/extra_arrivals/Arrivales-59-1.jpg', price: 1500, productName: "Piston Basic (Handsfree)" ,zoom1:"/PicturesFiles/extra_arrivals/Arrivales-59-1.jpg",zoom2:"/PicturesFiles/extra_arrivals/Arrivales-60.jpg",zoom3:""},
    { proID: 31,quantity:0, Features: `Key Features:<li>Max. Speed: 20km/h (maximum speed for each mode / Walking Mode: 6km/h / D: 15km/h / S: 20km/h)</li><li>Travel Range: 18Km</li><li>Dimensions: 1088 × 420 × 1173 mm</li><li>Product Weight: 13.7kg</li><li>Max. incline: 10%</li><li>Braking: E-ABS and drum brakes</li><li>Rated Motor Power: 250W</li><li>Max Motor Power: 450W</li><li>Tires: Front and rear 8.1" radial hollow run-flat tires</li><li>Max. load: 90Kg</li><li>Rider Height: 120-200cm</li><li>Rider Age: 16–50 years old</li><li>Working Temperature: 10°C - 40°C</li><li>Storage Temperature: -20°C - 45°C</li><li>IP Rating: IPX4</li><li>Charging Time: Approx.6 hours</li>`,key:``, BOX:``,descri:`<li>Battery Model: NEEF2208A</li><li>Rated Capacity: 165Wh</li><li>Charging temperature: 0°C - 44°C</li>`,note: 'Battery Specifications:', cateory: 'Lifestyle', img: '/PicturesFiles/extra_arrivals/Arrivales-61-1.jpg', price: 174999, productName: "Xiaomi Electric Scooter 4 Go" ,zoom1:"/PicturesFiles/extra_arrivals/Arrivales-61-1.jpg",zoom2:"",zoom3:""},
    { proID: 32,quantity:0, Features: `Key Features:<li>Max. speed: 25km/h (maximum speed for each mode: Walking mode: 6km/h; D: 20km/h; S: 25km/h)</li><li>Travel Range: Approx. 20km</li><li>Max. incline: Approx. 14%</li><li>Product Weight: 15.6kg</li><li>Braking: Front E-ABS + rear drum brake</li><li>Rated motor power: 300W</li><li>Max. motor power: 600W</li><li>Tires: 8.5" pneumatic tire</li><li>Max. Load: 100kg</li><li>Rider height: 120cm-200cm</li><li>Rider age: Age 16-50</li><li>Working temperature: -10°C ~ 40°C</li><li>Storage temperature</li><li>IP Rating: IP54</li><li>Charging Time: Approx. 4.5 hours</li>`,key:``, BOX:``,descri:`<li>Battery Model: P2185-BA2A</li><li>Rated Capacity: 5200mAh/187Wh</li><li>Charging temperature range: 0°C ~ 40°C</li>`,note: 'Battery Specifications: Lithium-ion battery', cateory: 'Lifestyle', img: '/PicturesFiles/extra_arrivals/Arrivales-62-1.jpg', price: 189999, productName: "Xiaomi Electric Scooter 4 Lite" ,zoom1:"/PicturesFiles/extra_arrivals/Arrivales-62-1.jpg",zoom2:"",zoom3:""},
    { proID: 33,quantity:0, Features: `<li>Product model no: MJDDLSD001QW</li><li>Maximum torque: 5 N.m</li><li>12 S2 Steel Bits</li><li>No-load speed: 200 r/min</li><li>Battery: 2000-mAh High-capacity Battery</li><li>Charging time: 120–180 min</li><li>Standards implemented: GB 3883.1-2014</li><li>Precision bit type: C6.3 × 25 mm</li><li>Phillips-head: PH1/PH2/PH3</li><li>Net weight of screwdriver: Approx. 350 g</li><li>Screwdriver dimensions: 124 × 130.5 × 42 mm</li><li>Rated voltage: 3.6V</li><li>Hex: H3/H4/H5</li><li>Slotted: SL4/SL6</li><li>Star: T15/T20/T25</li><li>Pozidriv: PZ2</li><li>Extension rod length: 60 mm</li>`,key:``, BOX:``,descri:``,note: '', cateory: 'Lifestyle', img: '/PicturesFiles/extra_arrivals/Arrivales-63-1.jpg', price: 8499, productName: "Mi Cordless Screwdriver",zoom1:"/PicturesFiles/extra_arrivals/Arrivales-63-1.jpg",zoom2:"",zoom3:"" },
    { proID: 34,quantity:0, Features: `<li>Material: Steel cable, ABS, zinc alloy</li><li>Stylish design | Comfortable grip | Five-digit code | 1200mm steel cable | Eco-friendly and durable</li><li>Net Weight: 0.27kg</li><li>Compatible vehicles: Mi Electric Scooter</li><li>Lock Diameter x Total Length: Φ 12 x 1200mm</li><li>Five-digit code — for an enhanced security</li>`,key:``, BOX:``,descri:`<li>Cable Lock</li><li>User Manual</li>`,note: 'PACKAGE CONTENTS:', cateory: 'Lifestyle', img: '/PicturesFiles/extra_arrivals/Arrivales-64-1.jpg', price: 5899, productName: "Xiaomi Electric Scooter Cable Lock" ,zoom1:"/PicturesFiles/extra_arrivals/Arrivales-64-1.jpg",zoom2:"",zoom3:""},
    { proID: 35,quantity:0, Features: `Material:<li>Textured PU material on the outside</li><li>Impact-resistant EVA material in the middle</li><li>Skin-friendly fabric on the inside</li>Protections<li>Drop Protection</li><li>Shock Absorption</li><li>Deformation Resistance</li>Special Features<li>Special Features</li><li>Versatility</li><li>Easy assembly and disassembly</li><li>Solid hard Case</li><li>Easy Access to Items</li><li>Watertight Zip</li>`,key:``, BOX:``,descri:`<li>Bag</li><li>User Manual</li><li>Hang Tags</li>`,note: 'INSIDE THE BOX', cateory: 'Lifestyle', img: '/PicturesFiles/extra_arrivals/Arrivales-66-1.jpg', price: 6399, productName: "Xiaomi Electric Scooter Storage Bag" ,zoom1:"/PicturesFiles/extra_arrivals/Arrivales-66-1.jpg",zoom2:"",zoom3:""},
    { proID: 36,quantity:0, Features: `Key Features:<li>Display: 6.67" AMOLED DotDisplay - SGS Eye Care Display</li><li>Resolution: 2400 x 1080</li><li>Refresh rate: 120Hz - Seamless Pro</li><li>Chipset: Snapdragon® 685 – 6nm</li><li>CPU: Octa-core CPU, up to 2.8GHz</li><li>Rear camera: 50MP main camera | 8MP ultra-wide camera | 2MP macro camera</li><li>Front Camera: 13MP front camera</li><li>Water & Dust Resistance: IP53</li><li>Charging: 33W fast charging | 33W in-box charger | USB-C</li><li>Cooling System: Graphite</li>`,key:``, BOX:``,descri:`<li>Security & Authentication: Side fingerprint sensor | AI Face Unlock</li><li>Connectivity: Dual SIM + microSD | Bluetooth 5.0</li><li>Vibration Motor: Coin vibration motor</li><li>Navigation: GPS: L1 ｜GLONASS: G1 | Compass: B1 | Galileo E1</li><li>Audio: 3.5mm headphone jack</li><li>Sensor: Proximity sensor | Ambient light sensor | Accelerometer | Electronic compass | IR blaster ｜Gyroscope</li><li>UI and system: MIUI 14 based on Android 13</li>`,note: 'General Features:', cateory: 'Details', img: '/PicturesFiles/extra_arrivals/Arrivales-67-1.jpg', price: 49999, productName: "Redmi Note 12 (8GB - 128GB) + Free Redmi Watch 3 Active" ,zoom1:"/PicturesFiles/extra_arrivals/Arrivales-67-1.jpg",zoom2:"/PicturesFiles/extra_arrivals/Arrivales-68.jpg",zoom3:"/PicturesFiles/extra_arrivals/Arrivales-68-2.jpg"},
    { proID: 37,quantity:0, Features: `Key Features :<li>Display: 6.74" Dot Drop display</li><li>Brightness: 450 nits (typ) | 600 nits HBM</li><li>Refresh Rate: Up to 90Hz</li><li>Corning® Gorilla® Glass screen</li><li>Processor: MediaTek Helio G85 processor - 12nm process | octa-core</li><li>CPU: Arm Cortex-A75 @ 2.0GHz</li><li>Rear Camera: Film Camera | HDR mode | Night mode | Portrait mode | 50MP mode | Time-lapse</li><li>50MP main camera | 2MP macro camera | Auxiliary lens</li><li>Front Camera: 8MP front Camera</li><li>Battery & Charging: 5000mAh (typ) | Supports 18W PD charging | USB Type-C</li>`,key:``, BOX:``,descri:`<li>Security: Side fingerprint sensor | AI face unlock</li><li>Network & Connectivity: Dual SIM + microSD | Supports 4G / 3G / 2G</li><li>Wireless Networks: Wi-Fi: 2.4GHz | 5GHz</li><li>Bluetooth 5.3</li><li>Navigation & Positioning: GPS | Glonass | Galileo | Beidou</li><li>Audio: 3.5mm headphone jack</li><li>Sensors: Virtual proximity sensor | Ambient light sensor | Accelerometer | Electronic compass</li><li>Operating System: MIUI 14 based on Android 13</li><li>Dimensions: Height: 168mm - Width: 78mm - Thickness: 8.09mm - Weight: 192g</li>`,note: 'General Features:', cateory: 'Details', img: '/PicturesFiles/extra_arrivals/Arrivales-68-1.jpg', price: 28099, productName: "Redmi 13C" ,zoom1:"/PicturesFiles/extra_arrivals/Arrivales-68-1.jpg",zoom2:"/PicturesFiles/extra_arrivals/Arrivales-69.jpg",zoom3:"/PicturesFiles/extra_arrivals/Arrivales-70.jpg"},
    { proID: 38,quantity:0, Features: `Key Features<li>Display: 6.79" FHD+ DotDisplay</li><li>Resolution: 2460x1080, 396 ppi</li><li>SGS Low Blue Light Certification</li><li>Processor: MediaTek Helio G88</li><li>GPU: Arm Mali-G52</li><li>Rear Camera: 50MP+8MP+2MP triple camera</li><li>Front Camera: 8MP camera</li><li>Battery & Charging: 5000mAh battery (typ) - Supports 18W fast charging</li><li>Water and Dust Resistant: IP53</li>`,key:``, BOX:``,descri:`<li>Security: Side fingerprint sensor - AI face unlock</li><li>Connectivity: SIM1 + Hybrid* (SIM or MicroSD)</li><li>*Hybrid slot can be used either for a second SIM or a MicroSD card(1TB expandable)</li><li>Sensors: Accelerometer | E-compass</li><li>Operating System: MIUI 14 based on Android 13</li><li>Audio: 3.5mm headphone jack</li><li>Navigation & Positioning: GPS | Glonass | Galileo | Beidou</li><li>Dimensions: Height: 168.60mm - Width: 76.28mm - Thickness: 8.17mm - Weight: 198.5g</li>`,note: 'General Features:', cateory: 'Details', img: '/PicturesFiles/extra_arrivals/Arrivales-71.jpg', price: 36999, productName: "Redmi 12 (4GB - 128GB)",zoom1:"/PicturesFiles/extra_arrivals/Arrivales-71.jpg",zoom2:"/PicturesFiles/extra_arrivals/Arrivales-72.jpg",zoom3:"/PicturesFiles/extra_arrivals/Arrivales-73.jpg" },
    { proID: 39,quantity:0, Features: `Key Features:<li>Display:  6.67" AMOLED Display</li><li>Refresh rate: Up to 120Hz</li><li>Resolution: 2400 x 1080</li><li>Processor: Snapdragon® 685 | 6nm manufacturing process technology</li><li>CPU: Octa-core CPU, up to 2.8GHz</li><li>GPU: Adreno 610</li><li>Rear Camera: Triple Camera</li><li>108MP main camera | 2MP macro camera | 8MP ultra wide camera</li><li>Front Camera: 16MP Front camera</li><li>Battery & Charging: 5000mAh (typ) | Supports 33W Fast charging  | 33W Fast charger in-box |  USB-C</li><li>Water and Dust Resistant: IP54</li>`,key:``, BOX:``,descri:`<li>Security: In-screen fingerprint sensor | AI face unlock</li><li>Network & Connectivity: SIM 1 + Hybrid (SIM or MicroSD) | Supports 4G / 3G / 2G</li><li>Sensors: Proximity sensor | Ambient light sensor | Accelerometer | Electronic compass</li><li>Operating System: MIUI 14</li><li>Audio: Dual Speakers | Dolby Atmos® | 3.5mm headphone jack</li><li>Navigation & Positioning: GPS: L1 | GLONASS: G1 | BDS: B1I | Galileo E1</li><li>Dimensions: Height: 162.24mm - Width: 75.55mm - Thickness: 7.97mm Weight: 188.5g</li>`,note: 'General Features:', cateory: 'Details', img: '/PicturesFiles/extra_arrivals/Arrivales-74.jpg', price: 52999, productName: "Redmi Note 13 (8GB-256GB)" ,zoom1:"/PicturesFiles/extra_arrivals/Arrivales-74.jpg",zoom2:"/PicturesFiles/extra_arrivals/Arrivales-75.jpg",zoom3:"/PicturesFiles/extra_arrivals/Arrivales-76.jpg" },
    { proID: 40,quantity:0, Features: `Key Features:<li>Display: 6.71” Dot Drop display</li><li>Resolution: 1650 x 720, 268 ppi</li><li>Brightness: 500 nits</li><li>Processors: MediaTek Helio G36</li><li>Refresh Rate: Up to 90Hz</li><li>CPU: Up to 2.2GHz</li><li>Rear Camera: 8MP AI Dual Camera</li><li>Auxiliary Lens | Film Camera | HDR Mode | Portrait Mode | Time Lapse</li><li>Flash & type: LED flash, monochrome</li><li>Front Camera: 5MP</li><li>Film Camera | HDR Mode | Soft Light Ring | Portrait Mode | Time Lapse</li><li>Battery Capacity : 5000 mAh (typ) | Support 10W Charging | 10W Type-C Inbox Charger</li><li>Security: Side Fingerprint Sensor | AI Face Unlock</li>`,key:``, BOX:``,descri:`<li>Network & Connectivity: Dual SIM + microSD | Support Dual 4G</li><li>Wireless Networks: 2.4GHz/5GHz Wi-Fi</li><li>Bluetooth 5.4</li><li>Navigation & Positioning: GPS | Glonass | Beidou | Galileo</li><li>Audio: 3.5mm headphone jack</li><li>Sensors: Virtual Ambient Light Sensor | Virtual Proximity Sensor | Accelerometer | Electronic Compass</li><li>Operating System: Android 14 | 2 Android Major Updates | 3 Years of Security Patch Update</li><li>Dimensions: Height: 168.4mm - Width: 76.3mm - Thickness: 8.3mm</li>`,note: 'General Features:', cateory: 'Details', img: '/PicturesFiles/extra_arrivals/Arrivales-77.jpg', price: 22999, productName: "Redmi A3 (4GB-128GB) + Free Piston Basic" ,zoom1:"/PicturesFiles/extra_arrivals/Arrivales-77.jpg",zoom2:"/PicturesFiles/extra_arrivals/Arrivales-78.jpg",zoom3:"/PicturesFiles/extra_arrivals/Arrivales-79.jpg"},
];descri:``,
localStorage.setItem("MiPakistan", JSON.stringify(data));



const productsDiv = document.getElementById('nick');
const power = document.getElementById('categories');

function over(input) {
    let codeList = '';
    power.style.display = "block";
    let filteredData = data.filter(x => x.cateory == input);
    // console.log(filteredData,'filter');
    filteredData.forEach((item) => {
        let cade =
            `
            <div class="element-row">
                <a href="/Charger.html?ProductID=${item.proID}"><img src="${item.img}" height='140px' alt="" class="" id="">
                <h6>${item.productName}</h6>
                <span class="text-danger"> Rs :${item.price}</span>
            </div>
            </a>
            `;
        codeList += cade;
    });

    productsDiv.innerHTML = codeList;

    let url = `/next.html?category=${encodeURIComponent(input)}`;

    let search =
        `
    <a href="${decodeURI(url)}" class="col-2 text-decoration-none">
        <div class="d-flex flex-column justify-content-center align-items-center">
            <img src="/5B4554A1-2C96-DBA2-9C56-0B14A672F827.png" alt="" class="">
            <span style="margin-top: -35px;" class="text-dark">VIEW MORE</span>
        </div>
    </a>
`;
    productsDiv.insertAdjacentHTML('beforeend', search);

    productsDiv.style.display = 'flex';
}


function out() {

    document.getElementById('categories').style.display = 'none';
}



function container() {
    productsDiv.style.display = 'flex';
    document.getElementById('categories').style.display = 'flex';
}

power.addEventListener("mouseenter", () => {
    power.style.display = "block";
    productsDiv.style.display = 'flex';
});



power.addEventListener("mouseleave", () => {
    power.style.display = "none";
    productsDiv.style.display = 'none';
});

// Hamburger-nev  @Media
if (window.innerWidth <= 767) {
    document.querySelector("#hamburger-nev").addEventListener('click', () => {
        document.querySelector("#first").style.left = "0";
    })
    document.querySelector("#left").addEventListener("click", () => {
        document.querySelector("#first").style.left = "-100%";
    })
}





// Local Storage Function: 

function getFromLocalStorage(localStorageKey = "MiPakistan") {
    return JSON.parse(localStorage.getItem(localStorageKey)) || [];
    
}

function saveToLocalStorage(localStorageKey = "MiPakistan", value) {
    const items = getFromLocalStorage();
    const newItems = [...items, value];

    localStorage.setItem("MiPakistan", JSON.stringify(newItems));
}

let result = [];
let updateResult = [];


const items = getFromLocalStorage();

const cartItems = document.getElementsByClassName('ViewPage');
let list = '';

const search = window.location.search;
const params = new URLSearchParams(search);
const categoryValue = params.get('category');
// console.log('params',categoryValue);

result = items.filter(x => x.cateory == categoryValue)
result.forEach((item) => {
    const cartItemHTML =
        `<a href="/Charger.html?ProductID=${item.proID}"> <div class="col-2" style="width: 18rem;">
            <img src="${item.img}" class="card-img-top">
            <div class="card-body">
                <p class="card-text">${item.productName}.</p>
                <h5 class="card-title text-danger"> Rs:${item.price}</h5>
            </div>
        </div> 
        </a>      
    `;

    list += cartItemHTML;
});


Array.from(cartItems).forEach(cartItem => {
    cartItem.innerHTML = list;
});

function count() {
    let cart = JSON.parse(localStorage.getItem('AddToCart')) || [];
    let totalquentity = 0;
    cart.forEach((item)=>{
        totalquentity += item.quantity;
    })
    let cartCount = document.querySelector('.cartCount');
    cartCount.innerHTML = totalquentity;
}
count();

// Shopping Bag Function;
const shoppingbag = document.getElementById('shopping-bag');
shoppingbag.addEventListener('mouseover',()=>{
    
})


let displayimagesearch = document.querySelector('.display-image-search');
function saveValue() {
    let searchValue = document.getElementById("Search-product").value.toUpperCase(),
    AllIConSvg = document.querySelector('.all-icons-svg'),
    DataPuch = '',
    DataPuchinnerHTML = '',
    abcd = data.filter(x => x.productName.toUpperCase().includes(searchValue));
    // searchValue.data.productName;
    abcd.forEach((item)=>{
        let searchDataPuch = 
        `
            <div class="" style="width: 10rem;">
            <img src="${item.img}" class="card-img-top" alt="...">
            <div class="card-body">
            <p class="card-text">${item.productName}.</p>
            <h5 class="card-title text-danger cart-prices">Rs.${item.price}</h5>
            </div>  
            </div>
        `
        DataPuch += searchDataPuch;
    })
    displayimagesearch.innerHTML = DataPuch;
    
    SearchProductName1 = data.filter(x => x.productName.includes(searchValue));

    let IconSvg =
    `
    <div class="icons">
        <i class="fa fa-solid fa-magnifying-glass"></i>
        <span>${searchValue}</span>
    </div>
    <div class="icons">
        <i class="fa fa-solid fa-magnifying-glass"></i>
        <span>${SearchProductName1[0].productName}</span>
    </div>
    <div class="icons">
        <i class="fa fa-solid fa-magnifying-glass"></i>
        <span>${SearchProductName1[1].productName}</span>
    </div>
    <div class="icons">
        <i class="fa fa-solid fa-magnifying-glass"></i>
        <span>${SearchProductName1[2].productName}</span>
    </div> 
    `;  
    DataPuchinnerHTML += IconSvg;
    AllIConSvg.innerHTML = DataPuchinnerHTML;

}

let SearchProduct = document.getElementById('Search-product');
if(SearchProduct){
    SearchProduct.addEventListener('keyup', () => {
        let NoItem = document.querySelector('.no-item');
        if (NoItem) {
          if (SearchProduct.value.trim() === '') {
              NoItem.style.visibility = 'hidden';
          } else {
              NoItem.style.visibility = 'visible';
          }
        }
      });
}



